// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOPabefWytzOFfFbBsysROBhMF-8rqWw',
    appId: '1:45695158720:web:dbf0d766afec317520e025',
    messagingSenderId: '45695158720',
    projectId: 'authentication-a9ea1',
    authDomain: 'authentication-a9ea1.firebaseapp.com',
    storageBucket: 'authentication-a9ea1.appspot.com',
    measurementId: 'G-BTJJM6M63Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTK7u7AOcDS3CT9M0ReQ9D9b6_Emci80',
    appId: '1:45695158720:android:45cc64a3713aec8a20e025',
    messagingSenderId: '45695158720',
    projectId: 'authentication-a9ea1',
    storageBucket: 'authentication-a9ea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnpbGmVdUfxag1zw9zdU7FJzUv58Llz9M',
    appId: '1:45695158720:ios:e667209e11982cc220e025',
    messagingSenderId: '45695158720',
    projectId: 'authentication-a9ea1',
    storageBucket: 'authentication-a9ea1.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnpbGmVdUfxag1zw9zdU7FJzUv58Llz9M',
    appId: '1:45695158720:ios:2c18e88e1e11df5020e025',
    messagingSenderId: '45695158720',
    projectId: 'authentication-a9ea1',
    storageBucket: 'authentication-a9ea1.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
